apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis
  namespace: gitlab
  labels:
    name: gitlab-redis
spec:
  selector:
    name: gitlab-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
