apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secret-job
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        name: generate-secret-job
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: tootsuite/mastodon:edge
        command: ["bundle", "exec", "rake", "secret"]
        env:
        - name: RAILS_ENV
          value: production
