apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-createuser-job
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        name: sentry-createuser-job
    spec:
      restartPolicy: Never
      containers:
      - name: app
        image: sentry:9.0.0
        command:
        - "sentry"
        - "createuser"
        - "--email"
        - "$(SENTRY_SUPERUSER_EMAIL)"
        - "--password"
        - "$(SENTRY_SUPERUSER_PASSWORD)"
        - "--superuser"
        env:
        - name: SENTRY_REDIS_HOST
          value: redis-service.default.svc.cluster.local
        - name: SENTRY_POSTGRES_HOST
          value: db-service.default.svc.cluster.local
        - name: SENTRY_DB_USER
          value: sentry
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-secret
              key: SENTRY_SECRET_KEY
        - name: SENTRY_SUPERUSER_EMAIL
          value: admin@example.com
        - name: SENTRY_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sentry-secret
              key: SENTRY_SUPERUSER_PASSWORD
