apiVersion: v1
kind: Service
metadata:
  name: mastodon-service
spec:
  selector:
    app: mastodon-web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  externalIPs:
  - {USER MINIKUBE IP}
